In [1]:
import numpy as np


In [2]:
my_list=[1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr=np.array([1,2,3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [18]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [24]:
np.linspace(1,11,25)

array([  1.        ,   1.41666667,   1.83333333,   2.25      ,
         2.66666667,   3.08333333,   3.5       ,   3.91666667,
         4.33333333,   4.75      ,   5.16666667,   5.58333333,
         6.        ,   6.41666667,   6.83333333,   7.25      ,
         7.66666667,   8.08333333,   8.5       ,   8.91666667,
         9.33333333,   9.75      ,  10.16666667,  10.58333333,  11.        ])

In [26]:
np.random.randint(3,8)

7

In [27]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [28]:
np.random.seed(101)
arr=np.random.randint(0,100,10)

In [29]:
arr.max()

95

In [30]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [31]:
mat=np.arange(0,100).reshape(10,10)

In [32]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
mat[4,5]

45

In [34]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [36]:
mat[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [37]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [38]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])