In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data= np.random.randint(0,100,(10,2))

In [5]:
data

array([[54, 78],
       [ 0, 59],
       [76, 99],
       [68, 75],
       [56,  9],
       [13, 84],
       [22,  1],
       [55, 13],
       [30, 53],
       [35, 85]])

In [6]:
scalar_model=MinMaxScaler()

In [7]:
type(scalar_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scalar_model.fit(data)

/home/biswas/anaconda3/envs/deeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scalar_model.transform(data)

array([[ 0.71052632,  0.78571429],
       [ 0.        ,  0.59183673],
       [ 1.        ,  1.        ],
       [ 0.89473684,  0.75510204],
       [ 0.73684211,  0.08163265],
       [ 0.17105263,  0.84693878],
       [ 0.28947368,  0.        ],
       [ 0.72368421,  0.12244898],
       [ 0.39473684,  0.53061224],
       [ 0.46052632,  0.85714286]])

In [10]:
scalar_model.fit_transform(data)

/home/biswas/anaconda3/envs/deeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.71052632,  0.78571429],
       [ 0.        ,  0.59183673],
       [ 1.        ,  1.        ],
       [ 0.89473684,  0.75510204],
       [ 0.73684211,  0.08163265],
       [ 0.17105263,  0.84693878],
       [ 0.28947368,  0.        ],
       [ 0.72368421,  0.12244898],
       [ 0.39473684,  0.53061224],
       [ 0.46052632,  0.85714286]])

In [13]:
import pandas as pd

In [14]:
mydata= np.random.randint(0,101,(50,4))

In [15]:
mydata


array([[ 58,  83,  63,  94],
       [ 15,  44,  63,  91],
       [ 73,  42,  44,  24],
       [ 71,  88,  24,  42],
       [ 39,  66,  21,  53],
       [ 50,  32,  73,  69],
       [ 17,  20,  43,  50],
       [ 99,  42,  37,  30],
       [  3,   4,  49,  33],
       [ 50,  60,  18,  10],
       [ 93,  52,  16,  61],
       [ 34,  66,  43,  46],
       [ 77,  34,  92,  69],
       [ 19,  33,  36,  27],
       [ 63,  99,  62,  12],
       [ 74,  44,  26,  22],
       [ 92,  31,  35,  87],
       [ 42,  66,  61,  19],
       [ 73,  63,  86,  14],
       [ 52,   5,  74,  34],
       [ 66,  87,  60,  23],
       [ 16,  24,  58,   6],
       [ 13,  11,  54,   8],
       [ 18,  24,  56,  76],
       [ 29, 100,  63,  56],
       [ 16,  75,  80,  99],
       [ 28,  76,  14,  80],
       [ 67,  84,   6,  55],
       [  6,  67,  94,  60],
       [ 49,  72,   7,  71],
       [ 76,  66,  22,  25],
       [ 98,  89,   6,   7],
       [ 34,  13,  92,   4],
       [ 89,  56,  17,  52],
       [ 95,  

In [19]:
df=pd.DataFrame(data=mydata, columns=['f1','f2','f3','f4'])

In [20]:
df

f1   f2  f3  f4
0   58   83  63  94
1   15   44  63  91
2   73   42  44  24
3   71   88  24  42
4   39   66  21  53
5   50   32  73  69
6   17   20  43  50
7   99   42  37  30
8    3    4  49  33
9   50   60  18  10
10  93   52  16  61
11  34   66  43  46
12  77   34  92  69
13  19   33  36  27
14  63   99  62  12
15  74   44  26  22
16  92   31  35  87
17  42   66  61  19
18  73   63  86  14
19  52    5  74  34
20  66   87  60  23
21  16   24  58   6
22  13   11  54   8
23  18   24  56  76
24  29  100  63  56
25  16   75  80  99
26  28   76  14  80
27  67   84   6  55
28   6   67  94  60
29  49   72   7  71
30  76   66  22  25
31  98   89   6   7
32  34   13  92   4
33  89   56  17  52
34  95    2  13  46
35  38   59   6  89
36  62    5  80  84
37  36   49  53  50
38  34   79  59   0
39  89   65  74  63
40  99   84  92  38
41  83   74  81  86
42  71   90  95  59
43  87   77  44  36
44  87   35  22  92
45  84   31  12  54
46  33   78  82  75
47   5   91  54  94
48  68   27  94  71
49  83   54  22  53

In [25]:
x=df[['f1','f2']]

In [26]:
x

f1   f2
0   58   83
1   15   44
2   73   42
3   71   88
4   39   66
5   50   32
6   17   20
7   99   42
8    3    4
9   50   60
10  93   52
11  34   66
12  77   34
13  19   33
14  63   99
15  74   44
16  92   31
17  42   66
18  73   63
19  52    5
20  66   87
21  16   24
22  13   11
23  18   24
24  29  100
25  16   75
26  28   76
27  67   84
28   6   67
29  49   72
30  76   66
31  98   89
32  34   13
33  89   56
34  95    2
35  38   59
36  62    5
37  36   49
38  34   79
39  89   65
40  99   84
41  83   74
42  71   90
43  87   77
44  87   35
45  84   31
46  33   78
47   5   91
48  68   27
49  83   54

In [30]:
y=df['f3']

In [31]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [36]:
x_test.shape

(15, 2)

In [37]:
x_train.shape

(35, 2)